### PR TITLE
Fix punctuation and capitalization errors

### PR DESCRIPTION
**Pull request by Jdrodriguez1228**
We shouldn't have passed this error to main.

### CODE REVIEW

**Review by juanito2707 — CHANGES_REQUESTED** [review]
Delete that new paragraph please.

**Comment by Jdrodriguez1228** [comment]
Changes made ✅

**Comment by Jdrodriguez1228** [comment]
> Delete that new paragraph please.

Changes made ✅.

**Review by juanito2707 — APPROVED** [review]
Excellent, that was!

**Pull request merged**
